name: Changeset Version

on:
  push:
    branches: [main]
    paths-ignore: ["README.md"]

jobs:
  version:
    runs-on: ubuntu-latest
    # For all pushes to main that do not have a commit message that starts with Version Packages, and thus aren't merging a versioning PR
    # Run the changesets action, which will either no-op if there are no changesets present,
    # or generate the Version Packages PR containing the updated version and merged release notes if there are changesets present
    if: ${{ !startsWith(github.event.commits[0].message, 'Version Packages') }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # Fixes issue identified in https://github.com/changesets/action/issues/70

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.12

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.*"
          cache: "pnpm"

      - uses: changesets/action@v1.3.0
        with:
          version: pnpm run ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_GITHUB_TOKEN }}
